mkdir "C:\Program Files\Idlewild-Lang\"
copy idlewild-lang.exe "C:\Program Files\Idlewild-Lang\"
copy libkoshka.core.dll "C:\Windows\System32"
copy libkoshka.mm.dll "C:\Windows\System32"
copy nasm.exe "C:\Program Files\Idlewild-Lang\"
copy FASM.EXE "C:\Program Files\Idlewild-Lang\"
copy GoLink.exe "C:\Program Files\Idlewild-Lang\"
copy *.dll "C:\Windows\System32"
