mkdir "C:\Program Files\Idlewild-Lang\"
copy idlewild-lang.exe "C:\Program Files\Idlewild-Lang\"
copy nasm.exe "C:\Program Files\Idlewild-Lang\"
copy FASM.EXE "C:\Program Files\Idlewild-Lang\"
copy GoLink.exe "C:\Program Files\Idlewild-Lang\"
copy libkoshka.core.dll "C:\Windows\System32\"
copy libkoshka.mm.dll "C:\Windows\System32\"
copy freeglut.dll "C:\Windows\System32\"
copy glew32.dll "C:\Windows\System32\"
copy libFLAC-8.dll "C:\Windows\System32\"
copy libfreetype-6.dll "C:\Windows\System32\"
copy libglib-2.0-0.dll "C:\Windows\System32\"
copy libiconv-2.dll "C:\Windows\System32\"
copy libintl-8.dll "C:\Windows\System32\"
copy libjpeg-9.dll "C:\Windows\System32\"
copy libmikmod-2.dll "C:\Windows\System32\"
copy libmodplug-1.dll "C:\Windows\System32\"
copy libogg-0.dll "C:\Windows\System32\"
copy libpng16-16.dll "C:\Windows\System32\"
copy libtiff-5.dll "C:\Windows\System32\"
copy libvorbis-0.dll "C:\Windows\System32\"
copy libvorbisfile-3.dll "C:\Windows\System32\"
copy libwebp-4.dll "C:\Windows\System32\"
copy SDL2.dll "C:\Windows\System32\"
copy SDL2_image.dll "C:\Windows\System32\"
copy SDL2_mixer.dll "C:\Windows\System32\"
copy SDL2_ttf.dll "C:\Windows\System32\"
copy smpeg2.dll "C:\Windows\System32\"
copy zlib1.dll "C:\Windows\System32\"
