rmdir /s /q "C:\Program Files\Idlewild-Lang\"
del C:\Windows\System32\libkoshka.core.dll
del C:\Windows\System32\libkoshka.mm.dll
del C:\Windows\System32\freeglut.dll
del C:\Windows\System32\glew32.dll
del C:\Windows\System32\libFLAC-8.dll
del C:\Windows\System32\libfreetype-6.dll
del C:\Windows\System32\libglib-2.0-0.dll
del C:\Windows\System32\libiconv-2.dll
del C:\Windows\System32\libintl-8.dll
del C:\Windows\System32\libjpeg-9.dll
del C:\Windows\System32\libmikmod-2.dll
del C:\Windows\System32\libmodplug-1.dll
del C:\Windows\System32\libogg-0.dll
del C:\Windows\System32\libpng16-16.dll
del C:\Windows\System32\libtiff-5.dll
del C:\Windows\System32\libvorbis-0.dll
del C:\Windows\System32\libvorbisfile-3.dll
del C:\Windows\System32\libwebp-4.dll
del C:\Windows\System32\SDL2.dll
del C:\Windows\System32\SDL2_image.dll
del C:\Windows\System32\SDL2_mixer.dll
del C:\Windows\System32\SDL2_ttf.dll
del C:\Windows\System32\smpeg2.dll
del C:\Windows\System32\zlib1.dll
